# Generated by Django 4.1.4 on 2023-01-02 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_artikel_kategori'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kategori',
            old_name='keteramgan',
            new_name='keterangan',
        ),
    ]
