# Generated by Django 4.1.4 on 2023-01-02 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_artikel_gambar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artikel',
            old_name='tamggal',
            new_name='tanggal',
        ),
    ]
